//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_ShipmentDetails
    {
        public string TrackingId { get; set; }
        public long OrderId { get; set; }
        public long DealerProductId { get; set; }
        public long DealerServiceId { get; set; }
        public decimal PackageWeight { get; set; }
    
        public virtual CMS_DealerProductCategory CMS_DealerProductCategory { get; set; }
        public virtual CMS_DealerService CMS_DealerService { get; set; }
        public virtual CMS_OrderInfo CMS_OrderInfo { get; set; }
    }
}
