//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_OrderInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_OrderInfo()
        {
            this.CMS_ShipmentDetails = new HashSet<CMS_ShipmentDetails>();
        }
    
        public long OrderId { get; set; }
        public long DealerId { get; set; }
        public long UserId { get; set; }
        public string FromAddressLine { get; set; }
        public string FromAreaName { get; set; }
        public string FromCityName { get; set; }
        public int FromPinCode { get; set; }
        public string ToName { get; set; }
        public string ToAddressLine { get; set; }
        public string ToAreaName { get; set; }
        public string ToCityName { get; set; }
        public int ToPinCode { get; set; }
        public string ToMobileNo { get; set; }
        public string ToEmail { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CMS_DealerInfo CMS_DealerInfo { get; set; }
        public virtual CMS_UserInfo CMS_UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_ShipmentDetails> CMS_ShipmentDetails { get; set; }
    }
}
