//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_DealerProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_DealerProductCategory()
        {
            this.CMS_DealerRate = new HashSet<CMS_DealerRate>();
            this.CMS_ShipmentDetails = new HashSet<CMS_ShipmentDetails>();
        }
    
        public long DealerProductId { get; set; }
        public long DealerId { get; set; }
        public long CategoryId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CMS_ProductCategoryMaster CMS_ProductCategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_DealerRate> CMS_DealerRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_ShipmentDetails> CMS_ShipmentDetails { get; set; }
        public virtual CMS_DealerInfo CMS_DealerInfo { get; set; }
    }
}
