//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_DealerRate
    {
        public long DealerRateId { get; set; }
        public long DealerId { get; set; }
        public long DealerProductId { get; set; }
        public long DealerServiceId { get; set; }
        public decimal PerCategoryPrice { get; set; }
        public decimal PerServicePrice { get; set; }
        public decimal PerKgPrice { get; set; }
        public decimal PerKmPrice { get; set; }
    
        public virtual CMS_DealerProductCategory CMS_DealerProductCategory { get; set; }
        public virtual CMS_DealerService CMS_DealerService { get; set; }
        public virtual CMS_DealerInfo CMS_DealerInfo { get; set; }
    }
}
